---
name: Container tag generator
author: Daryl Stark
description: GitHub action to generate container tags based on the branch

inputs:
  container-repository:
    description: The name for the repository for the container.
    required: true
  container-name:
    description: The name for the container. Defaults to the reponame
    required: false
    default: ""
  version:
    description: The version of the software. Used for a tag
    required: false

outputs:
  tags:
    description: The generated tags in a comma seperated list
    value: ${{ steps.tag-generator.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Set permissions for script
      id: permissions
      run: chmod +x ${{ github.action_path }}/src/generate-tags.sh
      shell: bash
    - name: Set container tags
      id: tag-generator
      env:
        INPUT_CONTAINER_REPOSITORY: ${{ inputs.container-repository }}
        INPUT_CONTAINER_NAME: ${{ inputs.container-name }}
        INPUT_VERSION: ${{ inputs.version }}
      run: ${{ github.action_path }}/src/generate-tags.sh
      shell: bash
