---
name: Container tag generator
author: Daryl Stark
description: GitHub action to generate container tags based on the branch

inputs:
  version:
    description: The version of the software. Used for a tag
    required: false

outputs:
  tags:
    description: The generated tags in a comma seperated list
    value: ${{ steps.tag-generator.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Set permissions for script
      id: tag-generator
      run: chmod +x ${{ github.action_path }}/src/generate-tags.sh
      shell: bash
    - name: Set container tags
      id: tag-generator
      run: ${{ github.action_path }}/src/generate-tags.sh "${{ inputs.version }}"
      shell: bash
